### ISSUE TITLE
Фикс вёрстки

### ISSUE THREAD

**Issue by Resaw-git** [antaliadom-team/frontend#72]
Поправить цвета и размеры элементов по всему приложению. Подробнее в Discordе ветка баги https://discord.com/channels/1054032384091230268/1054033778244333580/1074401765325287476

**Comment by zeroqs** [comment]
- [✔️] За фотографией по правому углу и до середины фото расположена фигура: прямоугольник без заливки оранжевые границы 

- [⛔] Стиль окна Вход: широкий прямоугольник ( Окно входа более узкое  (430х524), макеты (536х501) ) 

> У нас растянут на всю ширину правого столбца, задал ширину как в макете - особой разницы не увидел, или ее вообще нет

- [✔️] Заголовки полей E-mail, Пароль темно-синего цвета

- [✔️] В полях нет плейсхолдеров

- [✔️] Кнопка вход визуально сильно меньше


- [✔️] Нет аккаута? темно-синего цвета, Зарегистрироваться светло-оранжевого цвета, размер шрифта совпадает с Забыли пароль?

### Страница Личного кабинета

- [✔️] В шапке страницы вместо кнопки вход появляется Имя пользователя и первая буква фамилии с точкой Имя Ф.


- [⛔] Кнопка Добавить в избранное (сердечко) в ЛК

> _Заливка сердечка - белая. Т.к. объект добавлен в Избранное и отображается в ЛК - сердечко должно быть оранжевое_ - Я думаю это относится к функционалу добавления в избранное

- [⛔] Шапка при скролле закреплена в верхней части страницы

> Если шапка должна прокручиваться ей нужен bgc и ширину на весь экран. На данном этапе нужен только bgc

- [⛔] При нажатии на кнопку «Выйти из профиля» открывается страница Выхода из профиля ( Вы уверены, что хотите выйти из учетной записи?)
